version: '3.4'

services:
  idp:
    image: kristophjunge/test-saml-idp:1.15
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: ${SP_ENTITY_ID}
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: ${SP_ACS_URL}
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: ${SP_LOGOUT_URL}
      VIRTUAL_HOST: ${IDP_HOST}
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - ./authsources.php:/var/www/simplesamlphp/config/authsources.php
